### ISSUE TITLE
iApp too big for Heat DB

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-heat-plugins#52] opened 2016-04-15 09:49 UTC
Hi

When creating the following resource using the full_template property

```
type: F5::Sys::iAppTemplate
depends_on: [bigip_rsrc, partition]
properties:
  name:  { get_param: iapp_template_name }
  bigip_server: { get_resource: bigip_rsrc }
  partition: { get_resource: partition }
  full_template: { get_file: cloudband.dns.iapp }
```

It fails in the UIs with the following message

Resource CREATE failed: NonextantTemplateNameException: resources.iapp_template: Template name not found.

Looking in the heat-engine.log file it seems this turns out to be that the iApp template is too big for the column in the database:

2016-04-15 09:19:34.357 11388 ERROR oslo_db.sqlalchemy.exc_filters DataError: (1406, "Data too long for column 'resource_properties' at row 1")

I attach a file with the full heat-engine.log

Thanks

```
  Ulises
```

[heat-engine.log.txt](https://github.com/F5Networks/f5-openstack-heat-plugins/files/220694/heat-engine.log.txt)

**Comment by alonsocamaro** [comment] 2016-04-15 10:20
The file size is 70279 bytes and I'm including it in this update.

I'm using Mirantis 8.0 which is based in kilo.

[cloudband.dns.iapp.txt](https://github.com/F5Networks/f5-openstack-heat-plugins/files/220735/cloudband.dns.iapp.txt)

**Comment by alonsocamaro** [comment] 2016-04-15 11:09
I also tried with a minimalistic iapp of 1959 bytes and I found the same issue. See the iapp attached here.

[f5.hello_world.iapp.txt](https://github.com/F5Networks/f5-openstack-heat-plugins/files/220832/f5.hello_world.iapp.txt)

**Comment by swormke** [comment] 2016-04-15 12:16
@pjbreaux I thought that you had worked around this size limitation

**Comment by alonsocamaro** [comment] 2016-04-15 12:25
My plugin versions

root@node-7:~# pip list | grep f5
f5-icontrol-rest (1.0.2)
f5-openstack-heat-plugins (1.0.1a1)
f5-sdk (0.1.1)

Thanks

**Comment by pjbreaux** [comment] 2016-04-15 13:01
It requires an upgrade of the heat engine. I'll find the launchpad bug

**Comment by pjbreaux** [comment] 2016-04-15 13:42
Ulises, here is the fix specified by the Heat folks. It requires the Heat engine version 2015.1.3. Now, we are not specifying the exact Heat version in our install_requires for setup.py because we don't necessarily want our pip install to upgrade the Heat engine directly. This could cause issues if your Heat engine code and the dependencies were not installed with pip (but with apt or yum). So this is not a bug of the plugins. It may just be a documentation issue that I'll find a place for.

https://bugs.launchpad.net/heat/+bug/1493858

What is a bug is that the name of your template is f5.hello_world and our IappParser, which lives in f5-sdk, is breaking on the ('.') in your name. If you remove the period in your name, making it something like f5_hello_world. It should work. I have filed a [bug](https://github.com/F5Networks/f5-common-python/issues/344) in the f5-sdk to address this issue. I'll get all of this sorted out this weekend.

**Comment by pjbreaux** [comment] 2016-04-15 13:56
Actually putting the fix in f5-sdk in now.

**Comment by alonsocamaro** [comment] 2016-04-15 14:02
Ummm actually It seems I told you wrong: Mirantis 8.0 seems to be based in Liberty

root@node-7:~# dpkg -l | grep heat
ii  heat-api                             1:5.0.0-1~u14.04+mos43                 all          OpenStack orchestration service - ReST API
ii  heat-api-cfn                         1:5.0.0-1~u14.04+mos43                 all          OpenStack orchestration service - CFN API
ii  heat-api-cloudwatch                  1:5.0.0-1~u14.04+mos43                 all          OpenStack orchestration service - CloudWatch API
ii  heat-common                          1:5.0.0-1~u14.04+mos43                 all          OpenStack orchestration service - common files
ii  heat-docker                          1:5.0.0-1~u14.04+mos43                 all          OpenStack orchestration service docker resource
ii  heat-engine                          1:5.0.0-1~u14.04+mos43                 all          OpenStack orchestration service - engine
ii  python-heat                          1:5.0.0-1~u14.04+mos43                 all          OpenStack orchestration service - Python files
ii  python-heatclient                    0.8.0-1~u14.04+mos2                    all          client library and CLI for OpenStack Heat - Python 2.7

**Comment by pjbreaux** [comment] 2016-04-15 14:04
Did you try a different name for your template yet? Also, you should consider upgrading to the latest release of this repo, if you can. v7.0.2

**Comment by pjbreaux** [comment] 2016-04-15 14:12
Fix for name going into f5-sdk under [this pull request](https://github.com/F5Networks/f5-common-python/pull/345).

**Comment by pjbreaux** [comment] 2016-04-20 18:01
@alonsocamaro 

For the 'Data too long' error by sqlalchemy, you can see the bug and the fix in this launchpad bug:

https://bugs.launchpad.net/heat/+bug/1493858

**Comment by dflanigan** [comment] 2016-12-21 18:29
Closed because issue was fixed in f5-sdk.

**Closed as completed by dflanigan** 2016-12-21 18:29 UTC
Labels: bug
